
import java.io.DataInputStream;
import java.io.IOException;
import java.net.*;

/**
 * Created by mohammed on 1/31/16.
 */


// This class receives message and then classify them as either for ConnectResponse or ChatMessage
public class Receiver implements Runnable
{
    MulticastSocket MSOCK;
    String msg;
    Socket SOCK;
    static String [] Test = new String[100];

    private static String McastIP; //multicast ip used for a particular room

    public Receiver(Socket SOCK) throws IOException {
        this.SOCK = SOCK;
        DataInputStream dis = new DataInputStream(SOCK.getInputStream());
        msg = dis.readUTF();
        if (msg.contains("##clientId##") && msg.contains("$$McastIP&&")) {
            //  clientId = msg.substring(msg.lastIndexOf("#")+1, msg.indexOf("$"));
            McastIP = msg.substring(msg.lastIndexOf("&") + 1, msg.indexOf("%"));
            System.out.println("McastIP is " + McastIP);
        }
        InetAddress ia = InetAddress.getByName(McastIP);
        MSOCK = new MulticastSocket(8885);
        MSOCK.joinGroup(ia);
    }

    @Override
    public void run() { // multicast receiving

        // unicast receiving first // check message to whom?
        while (true) {
            DatagramPacket data = new DatagramPacket(new byte[1024], 1024);

            try {
                MSOCK.receive(data);
            } catch (IOException e) {
                e.printStackTrace();
            }
            String msg = new String(data.getData(), 0, data.getLength());
            if (msg.contains("User ")) {
                String TEMP = null;
                String User = msg.substring(msg.lastIndexOf("*")+1,(msg.indexOf("&")));
                if (msg.contains("****Joined the group****"))
                {
                    TEMP = msg.substring(msg.indexOf(" "), msg.lastIndexOf("****Joined the group****"));
                    ClientForm.TA_CONVERSATION.append(User + " has joined the group" + "\n");
                }
                if (msg.contains("****Left the group****")) {
                    TEMP = msg.substring(msg.indexOf(" "), msg.lastIndexOf("****Left the group****"));
                    ClientForm.TA_CONVERSATION.append(User + " has left the group" + "\n");
                }
                TEMP = TEMP.replace("[", "");  // Removing the brackets generated by the arraylist from the server
                TEMP = TEMP.replace("]", "");
                String[] CurrentUsers = TEMP.split(", ");
                ClientForm.JL_ONLINE.setListData(CurrentUsers);
            }
            else ClientForm.TA_CONVERSATION.append(msg + "\n");

        }
    }
}